import type { Root } from 'mdast'
import type { VFile } from 'vfile'
import { remark } from 'remark'
import remarkGfm from 'remark-gfm'
import { describe, expect, it } from 'vitest'
import type { MdatCheckOptions, Options } from '../src'
import remarkMdat, { mdatCheck } from '../src'

async function expandStringToVfile(markdown: string, options: Options): Promise<VFile> {
	return remark().use(remarkGfm).use(remarkMdat, options).process(markdown)
}

async function checkMarkdown(markdown: string, options: MdatCheckOptions): Promise<VFile> {
	return remark()
		.use(remarkGfm)
		.use(
			() =>
				// eslint-disable-next-line unicorn/consistent-function-scoping
				async function (tree, file) {
					// eslint-disable-next-line ts/no-unsafe-type-assertion
					await mdatCheck(tree as Root, file, options)
				},
		)
		.process(markdown)
}

function stripAnsiEscapeCodes(text: string): string {
	// This regex matches the escape sequences and removes them
	// eslint-disable-next-line no-control-regex
	const ansiEscapeRegex = /\u001B\[[\d;]*m/g
	return text.replaceAll(ansiEscapeRegex, '')
}

const options: Options = {
	rules: {
		'first-expansion': 'This is first',
		'optional-expansion': 'This is optional',
		'second-expansion': 'This is second',
	},
}

describe('check validation', () => {
	it('should not report errors when valid', async () => {
		const markdown = `<!-- first-expansion -->\n<!-- optional-expansion -->\n<!-- second-expansion -->`
		const result = await expandStringToVfile(markdown, options)
		const foundError = result.messages.some((message) => message.fatal === true)
		expect(foundError).toBeFalsy()
	})

	it('should warn when rules return nothing', async () => {
		const badOptions: Options = {
			...options,
			rules: {
				...options.rules,
				'rule-that-returns-nothing': '',
			},
		}
		const markdown = `<!-- first-expansion -->\n<!-- rule-that-returns-nothing -->\n<!-- optional-expansion -->\n<!-- second-expansion -->`
		const result = await expandStringToVfile(markdown, badOptions)
		const warnMessage = result.messages.find((message) => message.fatal === false)
		expect(warnMessage).toBeDefined()
		expect(stripAnsiEscapeCodes(warnMessage!.message)).toMatchInlineSnapshot(
			`"<!-- rule-that-returns-nothing --> returned an empty string."`,
		)
	})

	it('should report errors when rules throw errors', async () => {
		const badOptions: Options = {
			...options,
			rules: {
				...options.rules,
				'rule-that-throws'() {
					throw new Error('This rule throws')
				},
			},
		}
		const markdown = `<!-- rule-that-throws -->\n<!-- first-expansion -->\n<!-- optional-expansion -->\n<!-- second-expansion -->`
		const result = await expandStringToVfile(markdown, badOptions)
		const errorMessage = result.messages.find((message) => message.fatal === true)
		expect(errorMessage).toBeDefined()
		expect(stripAnsiEscapeCodes(errorMessage!.message)).toMatchInlineSnapshot(
			`"Caught error expanding <!-- rule-that-throws -->, Error message: "Failed to expand content: This rule throws""`,
		)
	})

	it('should report missing meta comments', async () => {
		const metaOptions: MdatCheckOptions = {
			addMetaComment: true,
			closingPrefix: '/',
			keywordPrefix: '',
			metaCommentIdentifier: '+',
			rules: { placeholder: 'This is a placeholder' },
		}
		const markdown = `<!-- placeholder -->\nThis is a placeholder\n<!-- /placeholder -->\n`
		const result = await checkMarkdown(markdown, metaOptions)
		const errorMessage = result.messages.find((message) => message.fatal === true)

		expect(errorMessage).toBeDefined()
		expect(stripAnsiEscapeCodes(errorMessage!.message)).toMatchInlineSnapshot(
			`"Missing meta comment"`,
		)
	})

	it('should report unwelcome meta comments', async () => {
		const metaOptions: MdatCheckOptions = {
			addMetaComment: false,
			closingPrefix: '/',
			keywordPrefix: '',
			metaCommentIdentifier: '+',
			rules: { placeholder: 'This is a placeholder' },
		}
		const markdown = `<!--+ Warning: Content inside HTML comment blocks was generated by mdat and may be overwritten. +-->\n<!-- placeholder -->\nThis is a placeholder\n<!-- /placeholder -->\n`
		const result = await checkMarkdown(markdown, metaOptions)
		const errorMessage = result.messages.find((message) => message.fatal === true)

		expect(errorMessage).toBeDefined()
		expect(stripAnsiEscapeCodes(errorMessage!.message)).toMatchInlineSnapshot(
			`"Unexpected meta comment"`,
		)
	})

	it('should report multiple meta comments when none are wanted', async () => {
		const metaOptions: MdatCheckOptions = {
			addMetaComment: false,
			closingPrefix: '/',
			keywordPrefix: '',
			metaCommentIdentifier: '+',
			rules: { placeholder: 'This is a placeholder' },
		}
		const markdown = `<!--+ Warning: Content inside HTML comment blocks was generated by mdat and may be overwritten. +-->\n<!--+ Warning: Content inside HTML comment blocks was generated by mdat and may be overwritten. +-->\n<!-- placeholder -->\nThis is a placeholder\n<!-- /placeholder -->\n`
		const result = await checkMarkdown(markdown, metaOptions)
		const errorMessage = result.messages.find(
			(message) => message.message === 'Multiple meta comments',
		)

		expect(errorMessage).toBeDefined()
		expect(stripAnsiEscapeCodes(errorMessage!.message)).toMatchInlineSnapshot(
			`"Multiple meta comments"`,
		)
	})

	it('should report multiple meta comments when a single one is wanted', async () => {
		const metaOptions: MdatCheckOptions = {
			addMetaComment: true,
			closingPrefix: '/',
			keywordPrefix: '',
			metaCommentIdentifier: '+',
			rules: { placeholder: 'This is a placeholder' },
		}
		const markdown = `<!--+ Warning: Content inside HTML comment blocks was generated by mdat and may be overwritten. +-->\n<!--+ Warning: Content inside HTML comment blocks was generated by mdat and may be overwritten. +-->\n<!-- placeholder -->\nThis is a placeholder\n<!-- /placeholder -->\n`
		const result = await checkMarkdown(markdown, metaOptions)
		const errorMessage = result.messages.find(
			(message) => message.message === 'Multiple meta comments',
		)

		expect(errorMessage).toBeDefined()
		expect(stripAnsiEscapeCodes(errorMessage!.message)).toMatchInlineSnapshot(
			`"Multiple meta comments"`,
		)
	})

	it('should warn about missing rules', async () => {
		const markdown = `<!-- mystery-comment -->\n<!-- first-expansion -->\n<!-- optional-expansion -->\n<!-- second-expansion -->`
		const result = await expandStringToVfile(markdown, options)
		const errorMessage = result.messages.find((message) => message.fatal === false) // "warn" level

		expect(errorMessage).toBeDefined()
		expect(stripAnsiEscapeCodes(errorMessage!.message)).toMatchInlineSnapshot(
			`"Missing rule for: <!-- mystery-comment -->"`,
		)
	})

	it('should warn about missing prefixes', async () => {
		const keywordOptions: Options = {
			...options,
			keywordPrefix: 'mm-',
		}
		const markdown = `<!-- mm-first-expansion -->\n<!-- optional-expansion -->\n<!-- mm-second-expansion -->`
		const result = await expandStringToVfile(markdown, keywordOptions)
		const errorMessage = result.messages.find((message) => message.fatal === false) // "warn" level

		expect(errorMessage).toBeDefined()
		expect(stripAnsiEscapeCodes(errorMessage!.message)).toMatchInlineSnapshot(
			`"Missing prefix: <!-- optional-expansion -->"`,
		)
	})

	it('should not warn about missing prefixes in non-rules', async () => {
		const keywordOptions: Options = {
			...options,
			keywordPrefix: 'mm-',
		}
		const markdown = `<!-- mm-first-expansion -->\n<!-- not-a-rule -->\n<!-- mm-second-expansion -->`
		const result = await expandStringToVfile(markdown, keywordOptions)
		const errorMessage = result.messages.find((message) => message.fatal === false) // "warn" level

		expect(errorMessage).not.toBeDefined()
	})

	it('should require meta comment when addMetaComment is a string', async () => {
		const metaOptions: MdatCheckOptions = {
			addMetaComment: 'Custom meta comment message',
			closingPrefix: '/',
			keywordPrefix: '',
			metaCommentIdentifier: '+',
			rules: { placeholder: 'This is a placeholder' },
		}
		const markdown = `<!-- placeholder -->\nThis is a placeholder\n<!-- /placeholder -->\n`
		const result = await checkMarkdown(markdown, metaOptions)
		const errorMessage = result.messages.find((message) => message.fatal === true)

		expect(errorMessage).toBeDefined()
		expect(stripAnsiEscapeCodes(errorMessage!.message)).toMatchInlineSnapshot(
			`"Missing meta comment"`,
		)
	})

	it('should not report errors when custom meta comment is present', async () => {
		const customMessage = 'Custom meta comment message'
		const metaOptions: MdatCheckOptions = {
			addMetaComment: customMessage,
			closingPrefix: '/',
			keywordPrefix: '',
			metaCommentIdentifier: '+',
			rules: { placeholder: 'This is a placeholder' },
		}
		const markdown = `<!--+ ${customMessage} +-->\n<!-- placeholder -->\nThis is a placeholder\n<!-- /placeholder -->\n`
		const result = await checkMarkdown(markdown, metaOptions)
		const foundError = result.messages.some((message) => message.fatal === true)

		expect(foundError).toBeFalsy()
	})
})
